import 'crossword_models.dart';

/// All static crossword puzzles (brain / focus themed).
final List<CrosswordPuzzle> crosswordPuzzles = [
  _puzzle1,
  _puzzle2,
  _puzzle3,
  _puzzle4,
  _puzzle5,
];

final _puzzle1 = CrosswordPuzzle(
  id: 'easy_5',
  titleAr: 'سهل — 5×5',
  titleEn: 'Easy — 5×5',
  grid: [
    ['ت', 'ر', 'ك', 'ي', 'ز'],
    ['ص', 'ح', 'ة', null, null],
    [null, 'د', 'م', 'ا', 'غ'],
    [null, 'ن', 'و', 'م', null],
    ['ذ', 'ا', 'ك', 'ر', 'ة'],
  ],
  clues: [
    const CrosswordClue(
      number: 1,
      direction: CrosswordDirection.across,
      clueTextAr: 'قدرة الذهن على التثبيت',
      clueTextEn: 'Ability to hold attention',
      answer: 'تركيز',
      startRow: 0,
      startCol: 4,
      length: 5,
    ),
    const CrosswordClue(
      number: 2,
      direction: CrosswordDirection.across,
      clueTextAr: 'العافية الجسدية',
      clueTextEn: 'Physical wellness',
      answer: 'صحة',
      startRow: 1,
      startCol: 2,
      length: 3,
    ),
    const CrosswordClue(
      number: 3,
      direction: CrosswordDirection.across,
      clueTextAr: 'مركز التفكير والإدراك',
      clueTextEn: 'Center of thought and perception',
      answer: 'دماغ',
      startRow: 2,
      startCol: 4,
      length: 4,
    ),
    const CrosswordClue(
      number: 4,
      direction: CrosswordDirection.across,
      clueTextAr: 'راحة الجسم الليلية',
      clueTextEn: 'Nightly body rest',
      answer: 'نوم',
      startRow: 3,
      startCol: 3,
      length: 3,
    ),
    const CrosswordClue(
      number: 5,
      direction: CrosswordDirection.across,
      clueTextAr: 'تخزين التجارب والمعلومات',
      clueTextEn: 'Stores experiences and information',
      answer: 'ذاكرة',
      startRow: 4,
      startCol: 4,
      length: 5,
    ),
  ],
);

final _puzzle2 = CrosswordPuzzle(
  id: 'medium_7',
  titleAr: 'متوسط — 7×7',
  titleEn: 'Medium — 7×7',
  grid: [
    ['د', 'و', 'ب', 'ا', 'م', 'ي', 'ن'],
    [null, null, null, null, null, null, null],
    [null, 'إ', 'ن', 'ت', 'ب', 'ا', 'ه'],
    [null, null, null, null, null, null, null],
    ['إ', 'ر', 'ا', 'د', 'ة', null, null],
    [null, null, null, null, null, null, null],
    [null, 'ه', 'د', 'و', 'ء', null, null],
  ],
  clues: [
    const CrosswordClue(
      number: 1,
      direction: CrosswordDirection.across,
      clueTextAr: 'ناقل مكافأة في الدماغ',
      clueTextEn: 'Brain reward messenger',
      answer: 'دوبامين',
      startRow: 0,
      startCol: 6,
      length: 7,
    ),
    const CrosswordClue(
      number: 2,
      direction: CrosswordDirection.across,
      clueTextAr: 'التركيز الذهني',
      clueTextEn: 'Mental focus',
      answer: 'انتباه',
      startRow: 2,
      startCol: 6,
      length: 6,
    ),
    const CrosswordClue(
      number: 3,
      direction: CrosswordDirection.across,
      clueTextAr: 'قوة الإرادة والاختيار',
      clueTextEn: 'Willpower and choice',
      answer: 'إرادة',
      startRow: 4,
      startCol: 4,
      length: 5,
    ),
    const CrosswordClue(
      number: 4,
      direction: CrosswordDirection.across,
      clueTextAr: 'سكينة وطمأنينة',
      clueTextEn: 'Calm and tranquility',
      answer: 'هدوء',
      startRow: 6,
      startCol: 4,
      length: 4,
    ),
  ],
);

final _puzzle3 = CrosswordPuzzle(
  id: 'hard_9',
  titleAr: 'صعب — 9×9',
  titleEn: 'Hard — 9×9',
  grid: [
    ['ع', 'ص', 'ب', 'و', 'ن', 'ا', 'ت', null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'ب', 'ر', 'و', 'ت', 'و', 'ك', 'و', 'ل'],
    [null, null, null, null, null, null, null, null, null],
    ['م', 'ق', 'ا', 'و', 'م', 'ة', null, null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'ا', 'ن', 'ض', 'ب', 'ا', 'ط', null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'و', 'ع', 'ي', null, null, null, null, null],
  ],
  clues: [
    const CrosswordClue(
      number: 1,
      direction: CrosswordDirection.across,
      clueTextAr: 'خلايا ناقلة الإشارات',
      clueTextEn: 'Signal-carrying cells',
      answer: 'عصبونات',
      startRow: 0,
      startCol: 6,
      length: 7,
    ),
    const CrosswordClue(
      number: 2,
      direction: CrosswordDirection.across,
      clueTextAr: 'خطة منظمة للتعافي',
      clueTextEn: 'Structured recovery plan',
      answer: 'بروتوكول',
      startRow: 2,
      startCol: 8,
      length: 8,
    ),
    const CrosswordClue(
      number: 3,
      direction: CrosswordDirection.across,
      clueTextAr: 'مواجهة الإغراءات',
      clueTextEn: 'Facing temptations',
      answer: 'مقاومة',
      startRow: 4,
      startCol: 5,
      length: 6,
    ),
    const CrosswordClue(
      number: 4,
      direction: CrosswordDirection.across,
      clueTextAr: 'التحكم الذاتي',
      clueTextEn: 'Self-control',
      answer: 'انضباط',
      startRow: 6,
      startCol: 6,
      length: 6,
    ),
    const CrosswordClue(
      number: 5,
      direction: CrosswordDirection.across,
      clueTextAr: 'الإدراك والوعي الذاتي',
      clueTextEn: 'Awareness and consciousness',
      answer: 'وعي',
      startRow: 8,
      startCol: 2,
      length: 3,
    ),
  ],
);

final _puzzle4 = CrosswordPuzzle(
  id: 'focus_7',
  titleAr: 'تركيز — 7×7',
  titleEn: 'Focus — 7×7',
  grid: [
    ['ت', 'ر', 'ك', 'ي', 'ز', null, null],
    [null, null, null, null, null, null, null],
    [null, 'د', 'م', 'ا', 'غ', null, null],
    [null, null, null, null, null, null, null],
    ['ن', 'و', 'م', null, null, null, null],
    [null, 'ص', 'ح', 'ة', null, null, null],
    ['ذ', 'ا', 'ك', 'ر', 'ة', null, null],
  ],
  clues: [
    const CrosswordClue(
      number: 1,
      direction: CrosswordDirection.across,
      clueTextAr: 'ثبات الانتباه',
      clueTextEn: 'Sustained attention',
      answer: 'تركيز',
      startRow: 0,
      startCol: 4,
      length: 5,
    ),
    const CrosswordClue(
      number: 2,
      direction: CrosswordDirection.across,
      clueTextAr: 'عضو التفكير',
      clueTextEn: 'Thinking organ',
      answer: 'دماغ',
      startRow: 2,
      startCol: 4,
      length: 4,
    ),
    const CrosswordClue(
      number: 3,
      direction: CrosswordDirection.across,
      clueTextAr: 'راحة ليلية',
      clueTextEn: 'Night rest',
      answer: 'نوم',
      startRow: 4,
      startCol: 2,
      length: 3,
    ),
    const CrosswordClue(
      number: 4,
      direction: CrosswordDirection.across,
      clueTextAr: 'عافية جسدية',
      clueTextEn: 'Physical wellness',
      answer: 'صحة',
      startRow: 5,
      startCol: 3,
      length: 3,
    ),
    const CrosswordClue(
      number: 5,
      direction: CrosswordDirection.across,
      clueTextAr: 'حفظ المعلومات',
      clueTextEn: 'Information storage',
      answer: 'ذاكرة',
      startRow: 6,
      startCol: 4,
      length: 5,
    ),
  ],
);

final _puzzle5 = CrosswordPuzzle(
  id: 'brain_9',
  titleAr: 'دماغ — 9×9',
  titleEn: 'Brain — 9×9',
  grid: [
    ['د', 'و', 'ب', 'ا', 'م', 'ي', 'ن', null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'إ', 'ن', 'ت', 'ب', 'ا', 'ه', null, null],
    [null, null, null, null, null, null, null, null, null],
    ['إ', 'ر', 'ا', 'د', 'ة', null, null, null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'ه', 'د', 'و', 'ء', null, null, null, null],
    [null, null, null, null, null, null, null, null, null],
    [null, 'ت', 'ر', 'ك', 'ي', 'ز', null, null, null],
  ],
  clues: [
    const CrosswordClue(
      number: 1,
      direction: CrosswordDirection.across,
      clueTextAr: 'ناقل المكافأة',
      clueTextEn: 'Reward messenger',
      answer: 'دوبامين',
      startRow: 0,
      startCol: 6,
      length: 7,
    ),
    const CrosswordClue(
      number: 2,
      direction: CrosswordDirection.across,
      clueTextAr: 'الانتباه الواعي',
      clueTextEn: 'Conscious attention',
      answer: 'انتباه',
      startRow: 2,
      startCol: 6,
      length: 6,
    ),
    const CrosswordClue(
      number: 3,
      direction: CrosswordDirection.across,
      clueTextAr: 'قوة القرار',
      clueTextEn: 'Decision strength',
      answer: 'إرادة',
      startRow: 4,
      startCol: 4,
      length: 5,
    ),
    const CrosswordClue(
      number: 4,
      direction: CrosswordDirection.across,
      clueTextAr: 'هدوء داخلي',
      clueTextEn: 'Inner calm',
      answer: 'هدوء',
      startRow: 6,
      startCol: 4,
      length: 4,
    ),
    const CrosswordClue(
      number: 5,
      direction: CrosswordDirection.across,
      clueTextAr: 'عمق التركيز',
      clueTextEn: 'Deep focus',
      answer: 'تركيز',
      startRow: 8,
      startCol: 4,
      length: 5,
    ),
  ],
);
